I0_columns:
- mon_3
- mon_4
I1_columns: xmap_roi00
data_directory: ../Data/ESRF_SNBL/Averaging/
standards_directory: ../Data/ESRF_SNBL/Averaging/
data_type: .dat
edge_correction: false
energy_column: ZapEnergy
energy_column_unitConversion: 1000
energy_unit: eV
temperature_unit: Â°C
save_directory: ./
temperature_column: null
xas_mode: Flourescence
